<%@ Page Title="" Language="C#" MasterPageFile="~/STOCK MANAGEMENT.master" AutoEventWireup="true" CodeFile="company.aspx.cs" Inherits="Default3" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    </asp:Content>
<asp:Content ID="Content2" runat="server" 
    contentplaceholderid="ContentPlaceHolder1">
    COMPANY INFO<br />
    <asp:DetailsView ID="DetailsView1" runat="server" 
        AutoGenerateInsertButton="True" AutoGenerateRows="False" BorderColor="#000099" 
        BorderStyle="Ridge" BorderWidth="50px" DataKeyNames="company_id" 
        DataSourceID="SqlDataSource1" DefaultMode="Insert" Height="50px" Width="125px">
        <Fields>
            <asp:BoundField DataField="company_id" HeaderText="company_id" 
                InsertVisible="False" ReadOnly="True" SortExpression="company_id" />
            <asp:BoundField DataField="company_name" HeaderText="company_name" 
                SortExpression="company_name" />
            <asp:BoundField DataField="address" HeaderText="address" 
                SortExpression="address" />
            <asp:BoundField DataField="contact" HeaderText="contact" 
                SortExpression="contact" />
            <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
        </Fields>
    </asp:DetailsView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionString2 %>" 
        DeleteCommand="DELETE FROM [company] WHERE [company_id] = @company_id" 
        InsertCommand="INSERT INTO [company] ([company_name], [address], [contact], [email]) VALUES (@company_name, @address, @contact, @email)" 
        SelectCommand="SELECT * FROM [company]" 
        UpdateCommand="UPDATE [company] SET [company_name] = @company_name, [address] = @address, [contact] = @contact, [email] = @email WHERE [company_id] = @company_id">
        <DeleteParameters>
            <asp:ControlParameter ControlID="GridView1" Name="company_id" 
                PropertyName="SelectedValue" Type="Decimal" />
        </DeleteParameters>
        <InsertParameters>
            <asp:ControlParameter ControlID="DetailsView1" Name="company_name" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="DetailsView1" Name="address" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="DetailsView1" Name="contact" 
                PropertyName="SelectedValue" Type="Decimal" />
            <asp:ControlParameter ControlID="DetailsView1" Name="email" 
                PropertyName="SelectedValue" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="GridView1" Name="company_name" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView1" Name="address" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView1" Name="contact" 
                PropertyName="SelectedValue" Type="Decimal" />
            <asp:ControlParameter ControlID="GridView1" Name="email" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView1" Name="company_id" 
                PropertyName="SelectedValue" Type="Decimal" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" BorderColor="#000099" BorderStyle="Groove" 
        BorderWidth="50px" AutoGenerateColumns="False" DataKeyNames="company_id" 
        DataSourceID="SqlDataSource1">
        <Columns>
            <asp:BoundField DataField="company_id" HeaderText="company_id" 
                InsertVisible="False" ReadOnly="True" SortExpression="company_id" />
            <asp:BoundField DataField="company_name" HeaderText="company_name" 
                SortExpression="company_name" />
            <asp:BoundField DataField="address" HeaderText="address" 
                SortExpression="address" />
            <asp:BoundField DataField="contact" HeaderText="contact" 
                SortExpression="contact" />
            <asp:BoundField DataField="email" HeaderText="email" SortExpression="email" />
        </Columns>
    </asp:GridView>
</asp:Content>


