<%@ Page Title="" Language="C#" MasterPageFile="~/STOCK MANAGEMENT.master" AutoEventWireup="true" CodeFile="productInfo.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
    .style5
    {
        text-decoration: underline;
            font-size: xx-large;
        }
    .style6
    {
        width: 100%;
    }
    .style9
    {
        font-size: x-large;
    }
    .style10
    {
            width: 312px;
            font-size: x-large;
            font-weight: bold;
        }
</style>
</asp:Content>
<asp:Content ID="Content2" runat="server" 
    contentplaceholderid="ContentPlaceHolder1">
    <p class="style5">
    <strong>Product Information</strong></p>
<table class="style6">
    <tr>
        <td class="style10">
            Product ID:</td>
        <td>
            <asp:TextBox ID="TextBox1" runat="server" CssClass="style9" Width="316px"></asp:TextBox>
        </td>
    </tr>
    <tr>
        <td class="style10">
            Name:</td>
        <td>
            <asp:TextBox ID="TextBox2" runat="server" CssClass="style9" Width="316px"></asp:TextBox>
        </td>
    </tr>
    <tr>
        <td class="style10">
            Company Name:</td>
        <td>
            <asp:TextBox ID="TextBox3" runat="server" CssClass="style9" Width="316px"></asp:TextBox>
        </td>
    </tr>
    <tr>
        <td class="style10">
            Manufacture Date:</td>
        <td>
            <asp:TextBox ID="TextBox4" runat="server" CssClass="style9" Width="316px"></asp:TextBox>
        </td>
    </tr>
    <tr>
        <td class="style10">
            Manufacture Exp.Date:</td>
        <td>
            <asp:TextBox ID="TextBox5" runat="server" CssClass="style9" Width="316px"></asp:TextBox>
        </td>
    </tr>
    <tr>
        <td class="style10">
            Serial No:</td>
        <td>
            <asp:TextBox ID="TextBox6" runat="server" CssClass="style9" Width="316px"></asp:TextBox>
        </td>
    </tr>
    <tr>
        <td class="style10">
            MRP Price:</td>
        <td>
            <asp:TextBox ID="TextBox7" runat="server" CssClass="style9" Width="316px"></asp:TextBox>
        </td>
    </tr>
    <tr>
        <td class="style10">
            Quantity:</td>
        <td>
            <asp:TextBox ID="TextBox8" runat="server" CssClass="style9" Width="316px"></asp:TextBox>
        </td>
    </tr>
    <tr>
        <td class="style10">
            Product Catagory:</td>
        <td>
            <asp:TextBox ID="TextBox9" runat="server" CssClass="style9" Width="316px"></asp:TextBox>
        </td>
    </tr>
    <tr>
        <td class="style10">
            Product Dealer:</td>
        <td>
            <asp:TextBox ID="TextBox10" runat="server" CssClass="style9" Width="316px"></asp:TextBox>
        </td>
    </tr>
</table>
<br />
<asp:Button ID="Button1" runat="server" Text="Submit" Width="182px" 
        style="font-size: x-large; font-weight: 700" onclick="Button1_Click" />
&nbsp;&nbsp;&nbsp;
<TR>
    <asp:GridView ID="GridView1" runat="server" Visible="False" 
        onselectedindexchanged="GridView1_SelectedIndexChanged">
    </asp:GridView>
    <br />
<asp:Button ID="Button_upd" runat="server" Text="UPDATE" Width="182px" 
        style="font-size: x-large; font-weight: 700" onclick="Button1_UPD_Click" />
<asp:Button ID="Button_DEL" runat="server" Text="DELETE" Width="182px" 
        style="font-size: x-large; font-weight: 700" onclick="Button1_DEL_Click" />
    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
        DataKeyNames="P_ID" DataSourceID="Sqlproduct" Visible="False" 
        onselectedindexchanged="GridView2_SelectedIndexChanged">
        <Columns>
            <asp:BoundField DataField="P_ID" HeaderText="P_ID" InsertVisible="False" 
                ReadOnly="True" SortExpression="P_ID" />
            <asp:BoundField DataField="PRODUCT_ID" HeaderText="PRODUCT_ID" 
                SortExpression="PRODUCT_ID" />
            <asp:BoundField DataField="NAME" HeaderText="NAME" SortExpression="NAME" />
            <asp:BoundField DataField="C_NAME" HeaderText="C_NAME" 
                SortExpression="C_NAME" />
            <asp:BoundField DataField="MANFU_DATE" HeaderText="MANFU_DATE" 
                SortExpression="MANFU_DATE" />
            <asp:BoundField DataField="EXP_DATE" HeaderText="EXP_DATE" 
                SortExpression="EXP_DATE" />
            <asp:BoundField DataField="SERIAL_NO" HeaderText="SERIAL_NO" 
                SortExpression="SERIAL_NO" />
            <asp:BoundField DataField="MRP" HeaderText="MRP" SortExpression="MRP" />
            <asp:BoundField DataField="QTY" HeaderText="QTY" SortExpression="QTY" />
            <asp:BoundField DataField="PRODUCT_CAT" HeaderText="PRODUCT_CAT" 
                SortExpression="PRODUCT_CAT" />
            <asp:BoundField DataField="PRODUCT_DEALER" HeaderText="PRODUCT_DEALER" 
                SortExpression="PRODUCT_DEALER" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="Sqlproduct" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ConnectionString2 %>" 
        DeleteCommand="DELETE FROM [PRODUCT_INFO] WHERE [P_ID] = @P_ID" 
        InsertCommand="INSERT INTO [PRODUCT_INFO] ([PRODUCT_ID], [NAME], [C_NAME], [MANFU_DATE], [EXP_DATE], [SERIAL_NO], [MRP], [QTY], [PRODUCT_CAT], [PRODUCT_DEALER]) VALUES (@PRODUCT_ID, @NAME, @C_NAME, @MANFU_DATE, @EXP_DATE, @SERIAL_NO, @MRP, @QTY, @PRODUCT_CAT, @PRODUCT_DEALER)" 
        SelectCommand="SELECT * FROM [PRODUCT_INFO]" 
        UpdateCommand="UPDATE [PRODUCT_INFO] SET [PRODUCT_ID] = @PRODUCT_ID, [NAME] = @NAME, [C_NAME] = @C_NAME, [MANFU_DATE] = @MANFU_DATE, [EXP_DATE] = @EXP_DATE, [SERIAL_NO] = @SERIAL_NO, [MRP] = @MRP, [QTY] = @QTY, [PRODUCT_CAT] = @PRODUCT_CAT, [PRODUCT_DEALER] = @PRODUCT_DEALER WHERE [P_ID] = @P_ID">
        <DeleteParameters>
            <asp:ControlParameter ControlID="GridView2" Name="P_ID" 
                PropertyName="SelectedValue" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="PRODUCT_ID" Type="String" />
            <asp:Parameter Name="NAME" Type="String" />
            <asp:Parameter Name="C_NAME" Type="String" />
            <asp:Parameter Name="MANFU_DATE" Type="String" />
            <asp:Parameter Name="EXP_DATE" Type="String" />
            <asp:Parameter Name="SERIAL_NO" Type="String" />
            <asp:Parameter Name="MRP" Type="String" />
            <asp:Parameter Name="QTY" Type="String" />
            <asp:Parameter Name="PRODUCT_CAT" Type="String" />
            <asp:Parameter Name="PRODUCT_DEALER" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="GridView2" Name="PRODUCT_ID" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView2" Name="NAME" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView2" Name="C_NAME" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView2" Name="MANFU_DATE" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView2" Name="EXP_DATE" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView2" Name="SERIAL_NO" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView2" Name="MRP" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView2" Name="QTY" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView2" Name="PRODUCT_CAT" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView2" Name="PRODUCT_DEALER" 
                PropertyName="SelectedValue" Type="String" />
            <asp:ControlParameter ControlID="GridView2" Name="P_ID" 
                PropertyName="SelectedValue" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
</asp:Content>


